
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
networks:
  rinkeby:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}